Chapter 02 단순선형회귀
================

## 2.0 library

``` r
library(ggplot2)
```

## 2.3

| Minutes | Units |
|--------:|------:|
|      23 |     1 |
|      29 |     2 |
|      49 |     3 |
|      64 |     4 |
|      74 |     4 |
|      87 |     5 |
|      96 |     6 |
|      97 |     6 |
|     109 |     7 |
|     119 |     8 |
|     149 |     9 |
|     145 |     9 |
|     154 |    10 |
|     166 |    10 |

``` r
df2_5 = read.table("https://www1.aucegypt.edu/faculty/hadi/RABE5/Data5/P031.txt", header = T)
ggplot(data = df2_5, aes(x = Units, y = Minutes)) + 
    geom_point()
```

![](Ch02_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
cor(df2_5$Minutes, df2_5$Units)
```

    ## [1] 0.9936987

## 2.5

모형적합은 `lm(Y~X)`을 이용하여 할 수 있다.

``` r
fit2_5 = lm(Minutes ~ Units, data = df2_5)
fit2_5$coefficients
```

    ## (Intercept)       Units 
    ##    4.161654   15.508772

![
\\text{Minutes} = 4.162 + 15.509 \\cdot \\text{Units}
](https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&space;%5Cbg_white&space;%0A%5Ctext%7BMinutes%7D%20%3D%204.162%20%2B%2015.509%20%5Ccdot%20%5Ctext%7BUnits%7D%0A "
\text{Minutes} = 4.162 + 15.509 \cdot \text{Units}
")

적합값과 잔차는 다음과 같다.

``` r
fit2_5$fitted.values
```

    ##         1         2         3         4         5         6         7         8 
    ##  19.67043  35.17920  50.68797  66.19674  66.19674  81.70551  97.21429  97.21429 
    ##         9        10        11        12        13        14 
    ## 112.72306 128.23183 143.74060 143.74060 159.24937 159.24937

``` r
fit2_5$residuals
```

    ##          1          2          3          4          5          6          7 
    ##  3.3295739 -6.1791980 -1.6879699 -2.1967419  7.8032581  5.2944862 -1.2142857 
    ##          8          9         10         11         12         13         14 
    ## -0.2142857 -3.7230576 -9.2318296  5.2593985  1.2593985 -5.2493734  6.7506266

## 2.6

![\\hat{\\sigma}](https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&space;%5Cbg_white&space;%5Chat%7B%5Csigma%7D "\hat{\sigma}")은
다음과 같다.

``` r
summary(fit2_5)$sigma
```

    ## [1] 5.391725

각 회귀계수가
![0](https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&space;%5Cbg_white&space;0 "0")이라는
가설검정의 결과는 다음과 같다.

``` r
summary(fit2_5)
```

    ## 
    ## Call:
    ## lm(formula = Minutes ~ Units, data = df2_5)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -9.2318 -3.3415 -0.7143  4.7769  7.8033 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)    4.162      3.355    1.24    0.239    
    ## Units         15.509      0.505   30.71 8.92e-13 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 5.392 on 12 degrees of freedom
    ## Multiple R-squared:  0.9874, Adjusted R-squared:  0.9864 
    ## F-statistic: 943.2 on 1 and 12 DF,  p-value: 8.916e-13

## 2.7

회귀계수에 대한
![95\\%](https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&space;%5Cbg_white&space;95%5C%25 "95\%")
신뢰구간은 다음과 같다.

``` r
confint(fit2_5, "Units", level = 0.95)
```

    ##          2.5 %   97.5 %
    ## Units 14.40851 16.60903

``` r
confint(fit2_5, "(Intercept)", level = 0.95)
```

    ##                 2.5 %   97.5 %
    ## (Intercept) -3.148482 11.47179

``` r
confint(fit2_5, level = 0.95)
```

    ##                 2.5 %   97.5 %
    ## (Intercept) -3.148482 11.47179
    ## Units       14.408512 16.60903

## 2.8

![x=4](https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&space;%5Cbg_white&space;x%3D4 "x=4")인
경우의 예측값은 다음과 같다.

``` r
predict(fit2_5, newdata = data.frame(Units = 4))
```

    ##        1 
    ## 66.19674

예측에 대한 신뢰구간은 다음과 같다.

``` r
predict(fit2_5, newdata = data.frame(Units = 4), interval = "prediction")
```

    ##        fit      lwr      upr
    ## 1 66.19674 53.83936 78.55413

평균반응에 대한 신뢰구간은 다음과 같다.

``` r
predict(fit2_5, newdata = data.frame(Units = 4), interval = "confidence")
```

    ##        fit      lwr      upr
    ## 1 66.19674 62.36271 70.03077

## 2.9

결정계수는 다음과 같다.

``` r
summary(fit2_5)$r.squared
```

    ## [1] 0.9874372

## 2.10

원점을 통과하는 회귀모형의 결과를 구할 때는 `lm(Y ~ X - 1)`을 이용한다.

## 2.11

예측변수를 가지지 않는 회귀모형의 결과를 구할 때는 `lm(Y ~ 1)`을
이용한다.
